name: (Frontend) Copy reops.json

on:
  push:
    paths:
      - 'frontend/public/repos.json'
    branches:
      - master
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest

    env:
      BOT_NAME: ${{ secrets.BOT_NAME }}
      BOT_EMAIL: ${{ secrets.BOT_EMAIL }}

    permissions:
      contents: write

    steps:
      - name: Checking out repository
        uses: actions/checkout@v4.1.1

      - name: Copy repos.json
        run: |
          cp "$GITHUB_WORKSPACE/public/repos.json" "$GITHUB_WORKSPACE/content/repos.json"

      - name: Commit changes
        run: |
          git config --local user.name "$BOT_NAME"
          git config --local user.email "$BOT_EMAIL"
          git pull
          git add .
          git commit -m "chore(repos): copy repos.json to content folder"
          git push
